baseURL: https://www.chuckvalenza.com/
languageCode: en-us
title: "Chuck Valenza"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: UA-180259949-1

# Enable Disqus forum
disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # background image of the landing page
  background: "images/background.png"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: images/logo-dark.png
    inverted: images/logo.png
    favicon: images/logo.png

  # GitHub repo URL of your site
  gitRepo: https://forge.shh.ninja/cvalenza/portfolio

  # specify whether you want to write blog post or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true
